#!/usr/bin/env bash
set -euo pipefail

mode="${1:-text}"

case "$mode" in
  text)
    pbpaste |
      perl -0777 -pe '
        s/\r\n/\n/g;
        s/[ \t]+$//mg;
        s/^[ \t]+//mg;
        s/\n{3,}/\n\n/g;
        s/(?<!\n)\n(?!\n)/ /g;
        s/ {2,}/ /g;
      ' |
      pbcopy
    ;;

  trim)
    pbpaste |
      perl -pe '
        s/\r\n/\n/g;
        s/^[ \t]+//g;
        s/[ \t]+$//g;
      ' |
      pbcopy
    ;;

  *)
    echo "Usage: cleanclip [text|trim]"
    exit 1
    ;;
esac
